using System.Globalization;

namespace SnipKey.Windows;

/// <summary>UI 문자열(영어·한국어·일본어). 키가 빠진 언어는 영어로 떨어진다.</summary>
internal static class Strings
{
    public static string Language { get; set; } = "system";

    private static string Effective =>
        Language != "system" ? Language
        : CultureInfo.CurrentUICulture.TwoLetterISOLanguageName switch { "ko" => "ko", "ja" => "ja", _ => "en" };

    public static string S(string key, params object[] args)
    {
        var table = Effective switch { "ko" => Ko, "ja" => Ja, _ => En };
        var format = table.TryGetValue(key, out var v) ? v : En.TryGetValue(key, out var e) ? e : key;
        return args.Length == 0 ? format : string.Format(CultureInfo.CurrentCulture, format, args);
    }

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.name"] = "SnipKey",
        ["tray.on"] = "Expansion On",
        ["tray.off"] = "Expansion Off",
        ["tray.exclude"] = "Don't Expand in {0}",
        ["tray.search"] = "Search Snippets… ({0})",
        ["tray.open"] = "Open SnipKey",
        ["tray.settings"] = "Settings…",
        ["tray.stats"] = "{0} snippets · {1} expansions",
        ["tray.quit"] = "Quit SnipKey",
        ["tab.snippets"] = "Snippets",
        ["tab.settings"] = "Settings",
        ["groups"] = "Groups",
        ["group.new"] = "New Group",
        ["group.add"] = "+ Group",
        ["group.rename"] = "Rename",
        ["group.delete"] = "Delete Group",
        ["group.enabled"] = "Group enabled",
        ["group.deleteConfirm"] = "Delete the group \"{0}\" and its {1} snippets?",
        ["search"] = "Search",
        ["snippet.add"] = "+ Snippet",
        ["snippet.duplicate"] = "Duplicate",
        ["snippet.delete"] = "Delete",
        ["snippet.deleteConfirm"] = "Delete the snippet \"{0}\"?",
        ["col.abbreviation"] = "Abbreviation",
        ["col.label"] = "Label",
        ["col.group"] = "Group",
        ["editor.abbreviation"] = "Abbreviation",
        ["editor.label"] = "Label",
        ["editor.content"] = "Content",
        ["editor.enabled"] = "Enabled",
        ["editor.caseSensitive"] = "Case sensitive",
        ["editor.adaptCase"] = "Adapt case",
        ["editor.adaptCase.help"] = "Type ;Sig for \"Best regards\", ;SIG for \"BEST REGARDS\"",
        ["editor.insertMacro"] = "Insert Macro",
        ["editor.preview"] = "Preview",
        ["editor.conflict"] = "Another enabled snippet uses \"{0}\" — only one of them can expand.",
        ["editor.empty"] = "Select a snippet, or add one.",
        ["macro.fillText"] = "Fill-in: single line",
        ["macro.fillArea"] = "Fill-in: multiple lines",
        ["macro.fillPopup"] = "Fill-in: popup menu",
        ["macro.fillPart"] = "Fill-in: optional section",
        ["macro.clipboard"] = "Clipboard",
        ["macro.date"] = "Date",
        ["macro.tomorrow"] = "Tomorrow's date",
        ["macro.time"] = "Time",
        ["macro.cursor"] = "Cursor position",
        ["macro.enter"] = "Press Enter",
        ["settings.expansion"] = "Enable expansion",
        ["settings.sound"] = "Play a sound when expanding",
        ["settings.undo"] = "Undo an expansion with Backspace",
        ["settings.login"] = "Start SnipKey when I sign in",
        ["settings.search"] = "Search palette shortcut",
        ["settings.language"] = "Language",
        ["settings.language.system"] = "System",
        ["settings.excluded"] = "Don't expand in these programs",
        ["settings.excluded.add"] = "Add Program…",
        ["settings.excluded.remove"] = "Remove",
        ["settings.library"] = "Snippet library",
        ["settings.library.saveAs"] = "Save Library As…",
        ["settings.library.link"] = "Link to Library…",
        ["settings.library.local"] = "Use Local Library",
        ["settings.library.hint"] = "To share snippets with a Mac, save the library into a folder both computers sync (iCloud Drive, Dropbox, OneDrive…) and link to that file on the other computer.",
        ["settings.library.linkFailed"] = "Could not use that library: {0}. Your current library is unchanged.",
        ["settings.import"] = "Import SnipKey JSON…",
        ["settings.import.done"] = "Imported {0} snippets in {1} groups.",
        ["settings.openFolder"] = "Open Data Folder",
        ["banner.readOnly"] = "SnipKey could not read your library, so changes are not being saved. A copy was kept at: {0}",
        ["banner.future"] = "This library was saved by a newer SnipKey. Update SnipKey to edit it.",
        ["banner.conflict"] = "Another computer changed the library while you had unsaved edits. Your version was kept at: {0}",
        ["banner.saveFailed"] = "Could not save the library.",
        ["fill.title"] = "Fill in: {0}",
        ["fill.include"] = "Include \"{0}\"",
        ["fill.insert"] = "Insert",
        ["fill.cancel"] = "Cancel",
        ["palette.placeholder"] = "Search abbreviation, label or content",
        ["palette.empty"] = "No matching snippets",
        ["notify.elevated"] = "SnipKey can't type into {0} because it is running as administrator.",
        ["notify.firstRun"] = "SnipKey is running in the notification area. Type ;hello to try it.",
        ["notify.hotkeyFailed"] = "The search shortcut {0} is used by another program.",
        ["starter.group"] = "Getting Started",
        ["starter.hello"] = "Hello from SnipKey! 👋",
    };

    private static readonly Dictionary<string, string> Ko = new()
    {
        ["tray.on"] = "확장 켜짐",
        ["tray.off"] = "확장 꺼짐",
        ["tray.exclude"] = "{0}에서 확장 안 함",
        ["tray.search"] = "스니펫 검색… ({0})",
        ["tray.open"] = "SnipKey 열기",
        ["tray.settings"] = "설정…",
        ["tray.stats"] = "스니펫 {0}개 · 확장 {1}회",
        ["tray.quit"] = "SnipKey 종료",
        ["tab.snippets"] = "스니펫",
        ["tab.settings"] = "설정",
        ["groups"] = "그룹",
        ["group.new"] = "새 그룹",
        ["group.add"] = "+ 그룹",
        ["group.rename"] = "이름 바꾸기",
        ["group.delete"] = "그룹 삭제",
        ["group.enabled"] = "그룹 사용",
        ["group.deleteConfirm"] = "\"{0}\" 그룹과 스니펫 {1}개를 삭제할까요?",
        ["search"] = "검색",
        ["snippet.add"] = "+ 스니펫",
        ["snippet.duplicate"] = "복제",
        ["snippet.delete"] = "삭제",
        ["snippet.deleteConfirm"] = "\"{0}\" 스니펫을 삭제할까요?",
        ["col.abbreviation"] = "약어",
        ["col.label"] = "레이블",
        ["col.group"] = "그룹",
        ["editor.abbreviation"] = "약어",
        ["editor.label"] = "레이블",
        ["editor.content"] = "내용",
        ["editor.enabled"] = "사용",
        ["editor.caseSensitive"] = "대소문자 구분",
        ["editor.adaptCase"] = "대소문자 따라가기",
        ["editor.adaptCase.help"] = ";Sig로 치면 첫 글자가, ;SIG로 치면 전부 대문자가 됩니다",
        ["editor.insertMacro"] = "매크로 삽입",
        ["editor.preview"] = "미리보기",
        ["editor.conflict"] = "켜진 다른 스니펫도 \"{0}\"을 씁니다 — 둘 중 하나만 확장됩니다.",
        ["editor.empty"] = "스니펫을 고르거나 새로 추가하세요.",
        ["macro.fillText"] = "채우기: 한 줄",
        ["macro.fillArea"] = "채우기: 여러 줄",
        ["macro.fillPopup"] = "채우기: 선택 목록",
        ["macro.fillPart"] = "채우기: 선택 구간",
        ["macro.clipboard"] = "클립보드",
        ["macro.date"] = "날짜",
        ["macro.tomorrow"] = "내일 날짜",
        ["macro.time"] = "시각",
        ["macro.cursor"] = "커서 위치",
        ["macro.enter"] = "Enter 누르기",
        ["settings.expansion"] = "확장 사용",
        ["settings.sound"] = "확장할 때 소리 내기",
        ["settings.undo"] = "백스페이스로 확장 되돌리기",
        ["settings.login"] = "로그인할 때 SnipKey 시작",
        ["settings.search"] = "검색 팔레트 단축키",
        ["settings.language"] = "언어",
        ["settings.language.system"] = "시스템",
        ["settings.excluded"] = "이 프로그램에서는 확장하지 않음",
        ["settings.excluded.add"] = "프로그램 추가…",
        ["settings.excluded.remove"] = "제거",
        ["settings.library"] = "스니펫 라이브러리",
        ["settings.library.saveAs"] = "라이브러리 다른 곳에 저장…",
        ["settings.library.link"] = "라이브러리 연결…",
        ["settings.library.local"] = "로컬 라이브러리 사용",
        ["settings.library.hint"] = "Mac과 스니펫을 함께 쓰려면 두 컴퓨터가 동기화하는 폴더(iCloud Drive, Dropbox, OneDrive…)에 라이브러리를 저장하고, 다른 컴퓨터에서 그 파일에 연결하세요.",
        ["settings.library.linkFailed"] = "그 라이브러리를 쓸 수 없습니다: {0}. 지금 쓰는 라이브러리는 그대로입니다.",
        ["settings.import"] = "SnipKey JSON 가져오기…",
        ["settings.import.done"] = "그룹 {1}개에서 스니펫 {0}개를 가져왔습니다.",
        ["settings.openFolder"] = "데이터 폴더 열기",
        ["banner.readOnly"] = "라이브러리를 읽지 못해 변경 사항을 저장하지 않습니다. 사본을 남겨 두었습니다: {0}",
        ["banner.future"] = "더 새로운 SnipKey가 저장한 라이브러리입니다. 편집하려면 SnipKey를 업데이트하세요.",
        ["banner.conflict"] = "저장하지 않은 편집이 있는 동안 다른 컴퓨터가 라이브러리를 바꿨습니다. 내 버전은 여기에 남겨 두었습니다: {0}",
        ["banner.saveFailed"] = "라이브러리를 저장하지 못했습니다.",
        ["fill.title"] = "채우기: {0}",
        ["fill.include"] = "\"{0}\" 포함",
        ["fill.insert"] = "넣기",
        ["fill.cancel"] = "취소",
        ["palette.placeholder"] = "약어, 레이블, 내용으로 검색",
        ["palette.empty"] = "일치하는 스니펫이 없습니다",
        ["notify.elevated"] = "{0}은(는) 관리자 권한으로 실행 중이라 SnipKey가 입력할 수 없습니다.",
        ["notify.firstRun"] = "SnipKey가 알림 영역에서 실행 중입니다. ;hello 를 입력해 보세요.",
        ["notify.hotkeyFailed"] = "검색 단축키 {0}을(를) 다른 프로그램이 쓰고 있습니다.",
        ["starter.group"] = "시작하기",
        ["starter.hello"] = "SnipKey에서 인사드려요! 👋",
    };

    private static readonly Dictionary<string, string> Ja = new()
    {
        ["tray.on"] = "展開オン",
        ["tray.off"] = "展開オフ",
        ["tray.exclude"] = "{0} では展開しない",
        ["tray.search"] = "スニペットを検索… ({0})",
        ["tray.open"] = "SnipKey を開く",
        ["tray.settings"] = "設定…",
        ["tray.stats"] = "スニペット {0} 件 · 展開 {1} 回",
        ["tray.quit"] = "SnipKey を終了",
        ["tab.snippets"] = "スニペット",
        ["tab.settings"] = "設定",
        ["groups"] = "グループ",
        ["group.new"] = "新規グループ",
        ["group.add"] = "+ グループ",
        ["group.rename"] = "名前を変更",
        ["group.delete"] = "グループを削除",
        ["group.enabled"] = "グループを有効にする",
        ["group.deleteConfirm"] = "グループ「{0}」とスニペット {1} 件を削除しますか？",
        ["search"] = "検索",
        ["snippet.add"] = "+ スニペット",
        ["snippet.duplicate"] = "複製",
        ["snippet.delete"] = "削除",
        ["snippet.deleteConfirm"] = "スニペット「{0}」を削除しますか？",
        ["col.abbreviation"] = "略語",
        ["col.label"] = "ラベル",
        ["col.group"] = "グループ",
        ["editor.abbreviation"] = "略語",
        ["editor.label"] = "ラベル",
        ["editor.content"] = "内容",
        ["editor.enabled"] = "有効",
        ["editor.caseSensitive"] = "大文字と小文字を区別",
        ["editor.adaptCase"] = "大文字小文字に合わせる",
        ["editor.adaptCase.help"] = ";Sig と入力すると先頭だけ、;SIG ならすべて大文字になります",
        ["editor.insertMacro"] = "マクロを挿入",
        ["editor.preview"] = "プレビュー",
        ["editor.conflict"] = "有効な別のスニペットも「{0}」を使っています — どちらか一方しか展開されません。",
        ["editor.empty"] = "スニペットを選ぶか、追加してください。",
        ["macro.fillText"] = "入力欄: 1 行",
        ["macro.fillArea"] = "入力欄: 複数行",
        ["macro.fillPopup"] = "入力欄: ポップアップ",
        ["macro.fillPart"] = "入力欄: オプション部分",
        ["macro.clipboard"] = "クリップボード",
        ["macro.date"] = "日付",
        ["macro.tomorrow"] = "明日の日付",
        ["macro.time"] = "時刻",
        ["macro.cursor"] = "カーソル位置",
        ["macro.enter"] = "Enter を押す",
        ["settings.expansion"] = "展開を有効にする",
        ["settings.sound"] = "展開時にサウンドを鳴らす",
        ["settings.undo"] = "Backspace で展開を取り消す",
        ["settings.login"] = "サインイン時に SnipKey を起動",
        ["settings.search"] = "検索パレットのショートカット",
        ["settings.language"] = "言語",
        ["settings.language.system"] = "システム",
        ["settings.excluded"] = "これらのプログラムでは展開しない",
        ["settings.excluded.add"] = "プログラムを追加…",
        ["settings.excluded.remove"] = "削除",
        ["settings.library"] = "スニペットライブラリ",
        ["settings.library.saveAs"] = "ライブラリを別の場所に保存…",
        ["settings.library.link"] = "ライブラリにリンク…",
        ["settings.library.local"] = "ローカルライブラリを使う",
        ["settings.library.hint"] = "Mac とスニペットを共有するには、両方のコンピュータが同期するフォルダ（iCloud Drive、Dropbox、OneDrive…）にライブラリを保存し、もう一方でそのファイルにリンクします。",
        ["settings.library.linkFailed"] = "そのライブラリは使えません: {0}。現在のライブラリはそのままです。",
        ["settings.import"] = "SnipKey JSON を読み込む…",
        ["settings.import.done"] = "{1} グループから {0} 件のスニペットを読み込みました。",
        ["settings.openFolder"] = "データフォルダを開く",
        ["banner.readOnly"] = "ライブラリを読み込めないため、変更は保存されません。コピーを保存しました: {0}",
        ["banner.future"] = "新しい SnipKey で保存されたライブラリです。編集するには SnipKey をアップデートしてください。",
        ["banner.conflict"] = "未保存の編集中に別のコンピュータがライブラリを変更しました。あなたの版はここに残しました: {0}",
        ["banner.saveFailed"] = "ライブラリを保存できませんでした。",
        ["fill.title"] = "入力: {0}",
        ["fill.include"] = "「{0}」を含める",
        ["fill.insert"] = "挿入",
        ["fill.cancel"] = "キャンセル",
        ["palette.placeholder"] = "略語・ラベル・内容で検索",
        ["palette.empty"] = "一致するスニペットはありません",
        ["notify.elevated"] = "{0} は管理者として実行されているため、SnipKey は入力できません。",
        ["notify.firstRun"] = "SnipKey は通知領域で実行中です。;hello と入力してみてください。",
        ["notify.hotkeyFailed"] = "検索ショートカット {0} は別のプログラムが使用しています。",
        ["starter.group"] = "はじめに",
        ["starter.hello"] = "SnipKey からこんにちは！ 👋",
    };

    /// <summary>테스트용: 언어별로 빠진 키. 비어 있어야 한다.</summary>
    internal static IEnumerable<string> MissingKeys() =>
        En.Keys.Where(k => k != "app.name").SelectMany(k =>
            new[] { ("ko", Ko), ("ja", Ja) }.Where(t => !t.Item2.ContainsKey(k)).Select(t => $"{t.Item1}:{k}"));
}
